SmartPantry/app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, Response, jsonify
from collections import Counter
from . import db
from .models import Producto
from .utils import CONFIDENCE_THRESHOLD, DISTANCIA_UMBRAL
from ultralytics import YOLO
import ollama
import speech_recognition as sr
import pyttsx3
import cv2

main = Blueprint('main', __name__)

model = YOLO("app/models/tfg_yolo11s.pt")

productos_identificados = []

engine = pyttsx3.init()

cap = cv2.VideoCapture(0)

@main.route('/')
def index():
    return redirect(url_for('main.despensa'))

@main.route('/despensa')
def despensa():
    productos = Producto.query.order_by(Producto.cantidad.desc()).all()

    return render_template('despensa.html', productos=productos)

@main.route('/identificar')
def identificar():
    productos_contados = Counter(productos_identificados)
    return render_template('identificar.html', productos_contados=productos_contados)

def calcular_distancia(caja1, caja2):
    """Calcular la distancia euclidiana entre dos cajas delimitadoras."""
    x1, y1, w1, h1 = caja1
    x2, y2, w2, h2 = caja2
    return ((x1 - x2)**2 + (y1 - y2)**2)**0.5

def es_nueva_deteccion(caja_nueva, cajas_anteriores):
    """Determina si una nueva detección es suficientemente distinta de las anteriores."""
    for _, caja_anterior in cajas_anteriores:
        if calcular_distancia(caja_nueva, caja_anterior) < DISTANCIA_UMBRAL:
            return False
    return True

def gen_frames():
    global productos_identificados
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame)
        result = results[0]

        annotated_frame = result.plot()

        nuevas_detecciones = []

        for pred in result.boxes.data:
            class_id = int(pred[5])
            class_name = model.names[class_id]
            confidence = float(pred[4])
            x_min, y_min, x_max, y_max = map(int, pred[:4])

            if confidence >= CONFIDENCE_THRESHOLD:
                caja_actual = (x_min, y_min, x_max - x_min, y_max - y_min)

                if es_nueva_deteccion(caja_actual, productos_identificados):
                    nuevas_detecciones.append((class_name, caja_actual))

        if nuevas_detecciones:
            productos_identificados.extend(nuevas_detecciones)

        ret, buffer = cv2.imencode('.jpg', annotated_frame)
        frame = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@main.route('/video_feed')
def video_feed():
    """Ruta para el streaming de video desde la cámara."""
    return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

@main.route('/get_products')
def get_products():
    productos_contados = Counter([producto for producto, _ in productos_identificados])

    return jsonify(productos_contados)

@main.route('/add_to_despensa', methods=['POST'])
def add_to_despensa():
    global productos_identificados
    productos_contados = Counter([producto for producto, _ in productos_identificados])

    for nombre_producto, cantidad in productos_contados.items():
        producto = Producto.query.filter_by(nombre=nombre_producto).first()
        if producto:
            cantidad_a_agregar = cantidad * producto.multiplicador
            producto.cantidad += cantidad_a_agregar
        else:
            nuevo_producto = Producto(nombre=nombre_producto, cantidad=cantidad, multiplicador=1.0)
            db.session.add(nuevo_producto)

    db.session.commit()

    productos_identificados.clear()

    return redirect(url_for('main.index'))

@main.route('/actualizar_cantidad/<int:producto_id>/<accion>', methods=['POST'])
def actualizar_cantidad(producto_id, accion):
    producto = Producto.query.get_or_404(producto_id)

    if accion == 'incrementar':
        producto.cantidad += 1
    elif accion == 'decrementar' and producto.cantidad > 0:
        producto.cantidad -= 1

    db.session.commit()
    return redirect(url_for('main.despensa'))

@main.route('/actualizar_cantidad_identificados/<producto_nombre>/<accion>', methods=['POST'])
def actualizar_cantidad_identificados(producto_nombre, accion):
    global productos_identificados

    for i, (nombre, caja) in enumerate(productos_identificados):
        if nombre == producto_nombre:
            if accion == 'incrementar':
                productos_identificados.append((nombre, caja))
            elif accion == 'decrementar':
                productos_identificados.pop(i)
            break

    return redirect(url_for('main.identificar'))

@main.route('/eliminar_producto_identificado/<producto_nombre>', methods=['POST'])
def eliminar_producto_identificado(producto_nombre):
    global productos_identificados

    productos_identificados = [(nombre, caja) for nombre, caja in productos_identificados if nombre != producto_nombre]

    return redirect(url_for('main.identificar'))

@main.route('/receta')
def generar_receta():
    productos = Producto.query.filter(Producto.cantidad > 0).all()
    
    if not productos:
        return render_template('receta.html', titulo="Sin Receta", ingredientes=[], instrucciones=["No tienes suficientes productos en la despensa para generar una receta."])
    
    nombres_productos = [producto.nombre for producto in productos]
    lista_ingredientes = ', '.join(nombres_productos)
    print(lista_ingredientes)
    prompt = f"""
        Genera una receta utilizando los siguientes ingredientes disponibles: {lista_ingredientes}.
        
        Intenta que sea una tortilla de patatas

        No añadas ningún comentario extra.

        Sigue estrictamente este formato:
        
        Título de la receta:
        
        Ingredientes:
         Enumera cada ingrediente de la receta.
        
        Instrucciones:
         Proporciona pasos claros y numerados para preparar la receta.
        
        Si no puedes generar una receta válida con todos los ingredientes proporcionados, crea una receta con los ingredientes disponibles de todos modos.
        """

    try:
        response = ollama.chat(
            model="llama3.1",
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )
        receta_generada = response["message"]["content"]

        titulo = ""
        ingredientes = []
        instrucciones = []
        
        secciones = receta_generada.split("\n\n")

        for seccion in secciones:
            if seccion.lower().startswith("título"):
                titulo = seccion.split(":", 1)[1].strip()
            elif seccion.lower().startswith("ingredientes"):
                ingredientes = seccion.split("\n")[1:]
            elif seccion.lower().startswith("instrucciones"):
                instrucciones = seccion.split("\n")[1:]

    except Exception as e:
        titulo = "Error"
        ingredientes = []
        instrucciones = [f"Error al generar la receta: {e}"]

    return render_template('receta.html', titulo=titulo, ingredientes=ingredientes, instrucciones=instrucciones)

def speak_text(text):
    """Función para que el asistente hable."""
    engine.say(text)
    engine.runAndWait()

@main.route('/voice_command', methods=['POST'])
def voice_command():
    """Manejar los comandos de voz para navegar entre las vistas."""
    recognizer = sr.Recognizer()

    if 'audio' not in request.files:
        return {'status': 'error', 'message': 'No audio found'}, 400

    audio_file = request.files['audio']
    try:
        with sr.AudioFile(audio_file) as source:
            audio_data = recognizer.record(source)
            voice_text = recognizer.recognize_google(audio_data, language="es-ES").lower()

        if "receta" in voice_text:
            speak_text("Llevándote a la vista de recetas")
            return redirect(url_for('main.generar_receta'))

        elif "identificar" in voice_text:
            speak_text("Llevándote a la vista de identificar productos")
            return redirect(url_for('main.identificar'))

        else:
            speak_text("No entendí el comando, por favor repite")
            return {'status': 'error', 'message': 'Comando no reconocido'}, 400

    except sr.UnknownValueError:
        speak_text("No pude entender lo que dijiste, intenta de nuevo.")
        return {'status': 'error', 'message': 'Error de reconocimiento de voz'}, 400

    except sr.RequestError:
        speak_text("No pude procesar tu solicitud.")
        return {'status': 'error', 'message': 'Error de solicitud a la API de reconocimiento de voz'}, 500

SmartPantry/app/templates/despensa.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Pantry</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/despensa.css') }}">
</head>
<body>
    <div class="container">
        <h1>Smart Pantry</h1>
        <div class="top-buttons">
            <a href="{{ url_for('main.identificar') }}" class="add-button">Escanear Productos</a>
            <a href="{{ url_for('main.generar_receta') }}" class="recipe-button">Generar Receta</a>
        </div>        
        <div class="pantry-list">
            <h2>Productos Almacenados</h2>
            <div class="product-grid">
                {% for producto in productos %}
                    <div class="product-card">
                        <img src="{{ url_for('static', filename='images/' + (producto.imagen if producto.imagen else 'default.jpg')) }}" alt="{{ producto.nombre }}" class="product-image {% if producto.cantidad == 0 %}zero-quantity{% endif %}">
                        <div class="product-name">{{ producto.nombre }}</div>
                        <div class="product-qty">
                            {% if producto.cantidad > 0 %}
                                <strong>{{ producto.cantidad }}</strong>
                            {% endif %}
                        </div>                        
                        <div class="qty-buttons">
                            <form method="POST" action="{{ url_for('main.actualizar_cantidad', producto_id=producto.id, accion='incrementar') }}">
                                <button type="submit" class="qty-button increment">+</button>
                            </form>
                            <form method="POST" action="{{ url_for('main.actualizar_cantidad', producto_id=producto.id, accion='decrementar') }}">
                                <button type="submit" class="qty-button decrement">-</button>
                            </form>
                        </div>                        
                    </div>
                {% endfor %}
            </div>            
        </div>
    </div>
</body>
</html>

SmartPantry/app/templates/identificar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Pantry</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/identificar.css') }}">
    <script>
        function getProducts() {
            fetch('/get_products')
                .then(response => response.json())
                .then(data => {
                    const productList = document.getElementById('productList');
                    productList.innerHTML = '';
                    for (const [producto, cantidad] of Object.entries(data)) {
                        const li = document.createElement('li');
                        li.classList.add('product-item');
                        li.innerHTML = `
                            <span class="product-name">${producto}</span>
                            <span class="product-qty-text">(x${cantidad})</span>
                            <div class="qty-buttons">
                                <form method="POST" action="/actualizar_cantidad_identificados/${producto}/incrementar">
                                    <button type="submit" class="qty-button increment">+</button>
                                </form>
                                <form method="POST" action="/actualizar_cantidad_identificados/${producto}/decrementar">
                                    <button type="submit" class="qty-button decrement">-</button>
                                </form>
                                <form method="POST" action="/eliminar_producto_identificado/${producto}">
                                    <button type="submit" class="qty-button delete">X</button>
                                </form>
                            </div>
                        `;
                        productList.appendChild(li);
                    }
                });
        }
        setInterval(getProducts, 2000);
        
    </script>
</head>
<body>
    <div class="container">
        <h1>Smart Pantry</h1>
        <div class="main-content">
            <div class="image-identification box">
                <h2>Captura de Video</h2>
                <div>
                    <img src="{{ url_for('main.video_feed') }}" style="width: 100%; height: auto;" alt="Video en vivo">
                </div>
            </div>
            <div class="product-list box">
                <h2>Productos Identificados</h2>
                <ul id="productList">
                </ul>
            </div>
        </div>
        <div class="add-to-pantry-container">
            <form method="POST" action="{{ url_for('main.add_to_despensa') }}">
                <button type="submit" class="add-to-pantry-button">Añadir a la Despensa</button>
            </form>
        </div>
    </div>
</body>
</html>

SmartPantry/app/templates/receta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titulo }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/receta.css') }}">
</head>
<body>
    <div class="container">
        <h1>{{ titulo }}</h1>
        
        <div class="receta-content">
            <div class="ingredientes-box">
                <h2>Ingredientes</h2>
                <ul>
                    {% for ingrediente in ingredientes %}
                        <li>{{ ingrediente }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="instrucciones-box">
                <h2>Instrucciones</h2>
                <ol>
                    {% for paso in instrucciones %}
                        <li>{{ paso }}</li>
                    {% endfor %}
                </ol>
            </div>
        </div>

        <div class="back-button">
            <a href="{{ url_for('main.despensa') }}" class="button">Volver a Despensa</a>
        </div>
    </div>
</body>
</html>